### ISSUE TITLE
peer to peer review 11/25/2022

### ISSUE THREAD

**Issue by jash-debug** [akos29/Leader-Board#5]
Hi @akos29  ,
Good job so far the project look great 👍🏼
Here are some suggestions to follow

- Kindly ensure to use the recommended spacing for JS best practices.

Optional
- [ ] Kindly try to minimize the colors of the webpage to 2 or three colors for aesthetic purposes.

👍 linter errors
✔️ reviewed project run on your machine
✔️ Used best practices
✔️ Used Github Flow
✔️ Work documented professionally
🎟️ Full Functional site

Please, as recommended among the [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md), kindly avoid the unnecessary use of blank lines in your code. This offers better readability to your code. This has many occurrences in your code.

**Comment by akos29** [comment]
Updated the recommendation accordingly. [Patch](https://github.com/akos29/Leader-Board/pull/6)
